version: '3.5'

services:
  jenkins_server:
    image: jenkins/jenkins
    container_name: jenkins_server
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose

volumes:
  jenkins_data:
    name: jenkins_data