FROM gocd/gocd-agent-ubuntu-20.04:v22.2.0
USER root
RUN apt-get update && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt-get install -y nodejs && \
    export SONAR_SCANNER_VERSION=4.7.0.2747 && \
    export SONAR_SCANNER_HOME=/godata/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux && \
    curl --create-dirs -sSLo /godata/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip && \
    unzip -o /godata/.sonar/sonar-scanner.zip -d /godata/.sonar/ && \
    apt-get clean
USER go